// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthGetHealthData, HealthGetHealthErrors, HealthGetHealthResponses, MessageKeysListMessageKeyIdsData, MessageKeysListMessageKeyIdsErrors, MessageKeysListMessageKeyIdsResponses, MessageKeysListMessageKeysData, MessageKeysListMessageKeysErrors, MessageKeysListMessageKeysResponses, MessagesGetMessageData, MessagesGetMessageErrors, MessagesGetMessageFacetsData, MessagesGetMessageFacetsErrors, MessagesGetMessageFacetsResponses, MessagesGetMessageResponses, MessagesListMessagesData, MessagesListMessagesErrors, MessagesListMessagesResponses, MessagesResetOverrideData, MessagesResetOverrideErrors, MessagesResetOverrideResponses, MessagesSaveOverrideData, MessagesSaveOverrideErrors, MessagesSaveOverrideResponses, PermissionsGetPermissionsData, PermissionsGetPermissionsErrors, PermissionsGetPermissionsResponses, SourcesCreateSourceData, SourcesCreateSourceErrors, SourcesCreateSourceResponses, SourcesDeleteSourceData, SourcesDeleteSourceErrors, SourcesDeleteSourceResponses, SourcesGetSourceData, SourcesGetSourceErrors, SourcesGetSourceResponses, SourcesListSourcesData, SourcesListSourcesErrors, SourcesListSourcesResponses, SourcesListSourceSyncsData, SourcesListSourceSyncsErrors, SourcesListSourceSyncsResponses, SourcesSyncSourceData, SourcesSyncSourceErrors, SourcesSyncSourceResponses, SourcesTestSourceConfigurationData, SourcesTestSourceConfigurationErrors, SourcesTestSourceConfigurationResponses, SourcesTestSourceData, SourcesTestSourceErrors, SourcesTestSourceResponses, SourcesUpdateSourceData, SourcesUpdateSourceErrors, SourcesUpdateSourceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class TranslationsService {
    public static messagesGetMessageFacets<ThrowOnError extends boolean = false>(options?: Options<MessagesGetMessageFacetsData, ThrowOnError>): RequestResult<MessagesGetMessageFacetsResponses, MessagesGetMessageFacetsErrors, ThrowOnError> {
        return (options?.client ?? client).get<MessagesGetMessageFacetsResponses, MessagesGetMessageFacetsErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/facets',
            ...options
        });
    }
    
    public static healthGetHealth<ThrowOnError extends boolean = false>(options?: Options<HealthGetHealthData, ThrowOnError>): RequestResult<HealthGetHealthResponses, HealthGetHealthErrors, ThrowOnError> {
        return (options?.client ?? client).get<HealthGetHealthResponses, HealthGetHealthErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/health',
            ...options
        });
    }
    
    public static messagesListMessages<ThrowOnError extends boolean = false>(options?: Options<MessagesListMessagesData, ThrowOnError>): RequestResult<MessagesListMessagesResponses, MessagesListMessagesErrors, ThrowOnError> {
        return (options?.client ?? client).get<MessagesListMessagesResponses, MessagesListMessagesErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/messages',
            ...options
        });
    }
    
    public static messagesGetMessage<ThrowOnError extends boolean = false>(options: Options<MessagesGetMessageData, ThrowOnError>): RequestResult<MessagesGetMessageResponses, MessagesGetMessageErrors, ThrowOnError> {
        return (options.client ?? client).get<MessagesGetMessageResponses, MessagesGetMessageErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/messages/{id}',
            ...options
        });
    }
    
    public static messageKeysListMessageKeys<ThrowOnError extends boolean = false>(options?: Options<MessageKeysListMessageKeysData, ThrowOnError>): RequestResult<MessageKeysListMessageKeysResponses, MessageKeysListMessageKeysErrors, ThrowOnError> {
        return (options?.client ?? client).get<MessageKeysListMessageKeysResponses, MessageKeysListMessageKeysErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/messages/keys',
            ...options
        });
    }
    
    public static messageKeysListMessageKeyIds<ThrowOnError extends boolean = false>(options?: Options<MessageKeysListMessageKeyIdsData, ThrowOnError>): RequestResult<MessageKeysListMessageKeyIdsResponses, MessageKeysListMessageKeyIdsErrors, ThrowOnError> {
        return (options?.client ?? client).get<MessageKeysListMessageKeyIdsResponses, MessageKeysListMessageKeyIdsErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/messages/keys/ids',
            ...options
        });
    }
    
    public static messagesSaveOverride<ThrowOnError extends boolean = false>(options?: Options<MessagesSaveOverrideData, ThrowOnError>): RequestResult<MessagesSaveOverrideResponses, MessagesSaveOverrideErrors, ThrowOnError> {
        return (options?.client ?? client).put<MessagesSaveOverrideResponses, MessagesSaveOverrideErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/messages/override',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static messagesResetOverride<ThrowOnError extends boolean = false>(options?: Options<MessagesResetOverrideData, ThrowOnError>): RequestResult<MessagesResetOverrideResponses, MessagesResetOverrideErrors, ThrowOnError> {
        return (options?.client ?? client).post<MessagesResetOverrideResponses, MessagesResetOverrideErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/messages/override/reset',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static permissionsGetPermissions<ThrowOnError extends boolean = false>(options?: Options<PermissionsGetPermissionsData, ThrowOnError>): RequestResult<PermissionsGetPermissionsResponses, PermissionsGetPermissionsErrors, ThrowOnError> {
        return (options?.client ?? client).get<PermissionsGetPermissionsResponses, PermissionsGetPermissionsErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/permissions',
            ...options
        });
    }
    
    public static sourcesListSources<ThrowOnError extends boolean = false>(options?: Options<SourcesListSourcesData, ThrowOnError>): RequestResult<SourcesListSourcesResponses, SourcesListSourcesErrors, ThrowOnError> {
        return (options?.client ?? client).get<SourcesListSourcesResponses, SourcesListSourcesErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources',
            ...options
        });
    }
    
    public static sourcesCreateSource<ThrowOnError extends boolean = false>(options?: Options<SourcesCreateSourceData, ThrowOnError>): RequestResult<SourcesCreateSourceResponses, SourcesCreateSourceErrors, ThrowOnError> {
        return (options?.client ?? client).post<SourcesCreateSourceResponses, SourcesCreateSourceErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static sourcesDeleteSource<ThrowOnError extends boolean = false>(options: Options<SourcesDeleteSourceData, ThrowOnError>): RequestResult<SourcesDeleteSourceResponses, SourcesDeleteSourceErrors, ThrowOnError> {
        return (options.client ?? client).delete<SourcesDeleteSourceResponses, SourcesDeleteSourceErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources/{id}',
            ...options
        });
    }
    
    public static sourcesGetSource<ThrowOnError extends boolean = false>(options: Options<SourcesGetSourceData, ThrowOnError>): RequestResult<SourcesGetSourceResponses, SourcesGetSourceErrors, ThrowOnError> {
        return (options.client ?? client).get<SourcesGetSourceResponses, SourcesGetSourceErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources/{id}',
            ...options
        });
    }
    
    public static sourcesUpdateSource<ThrowOnError extends boolean = false>(options: Options<SourcesUpdateSourceData, ThrowOnError>): RequestResult<SourcesUpdateSourceResponses, SourcesUpdateSourceErrors, ThrowOnError> {
        return (options.client ?? client).put<SourcesUpdateSourceResponses, SourcesUpdateSourceErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static sourcesSyncSource<ThrowOnError extends boolean = false>(options: Options<SourcesSyncSourceData, ThrowOnError>): RequestResult<SourcesSyncSourceResponses, SourcesSyncSourceErrors, ThrowOnError> {
        return (options.client ?? client).post<SourcesSyncSourceResponses, SourcesSyncSourceErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources/{id}/sync',
            ...options
        });
    }
    
    public static sourcesListSourceSyncs<ThrowOnError extends boolean = false>(options: Options<SourcesListSourceSyncsData, ThrowOnError>): RequestResult<SourcesListSourceSyncsResponses, SourcesListSourceSyncsErrors, ThrowOnError> {
        return (options.client ?? client).get<SourcesListSourceSyncsResponses, SourcesListSourceSyncsErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources/{id}/syncs',
            ...options
        });
    }
    
    public static sourcesTestSource<ThrowOnError extends boolean = false>(options: Options<SourcesTestSourceData, ThrowOnError>): RequestResult<SourcesTestSourceResponses, SourcesTestSourceErrors, ThrowOnError> {
        return (options.client ?? client).post<SourcesTestSourceResponses, SourcesTestSourceErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources/{id}/test',
            ...options
        });
    }
    
    public static sourcesTestSourceConfiguration<ThrowOnError extends boolean = false>(options?: Options<SourcesTestSourceConfigurationData, ThrowOnError>): RequestResult<SourcesTestSourceConfigurationResponses, SourcesTestSourceConfigurationErrors, ThrowOnError> {
        return (options?.client ?? client).post<SourcesTestSourceConfigurationResponses, SourcesTestSourceConfigurationErrors, ThrowOnError>({
            security: [{
                    key: 'Backoffice-User',
                    scheme: 'bearer',
                    type: 'http'
                }],
            url: '/umbraco/management/api/v1/translations/sources/test',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
