// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type FacetResponse = {
    locales: Array<LocaleFacetResponse>;
    defaultLocale?: string | null;
    namespaces: Array<string>;
    totalKeys: number;
    outputEndpoints: Array<OutputEndpointResponse>;
    outputConflicts: Array<OutputConflictResponse>;
    statusCounts: {
        [key: string]: number;
    };
};

export type HttpTranslationHeaderOptions = {
    name: string;
    valueConfigurationKey: string;
};

export type HttpTranslationTransportOptions = {
    endpointTemplate: string;
    secretName?: string | null;
    timeoutSeconds: number;
    maximumResponseBytes: number;
    headers: Array<HttpTranslationHeaderOptions>;
};

export type LocaleFacetResponse = {
    code: string;
    name?: string | null;
    isDefault: boolean;
    isConfigured: boolean;
    messageCount: number;
    overriddenCount: number;
    needsReviewCount: number;
    absentKeyCount: number;
};

export type MessageCellResponse = {
    id: string;
    locale: string;
    defaultValue: string;
    overrideValue?: string | null;
    hasOverride: boolean;
    needsReview: boolean;
    truncated: boolean;
    state: MessageLocaleState;
    version?: number | null;
    updatedAt?: string | null;
    updatedBy?: string | null;
};

export type MessageConflictResponse = {
    code: string;
    message: string;
    currentVersion?: number | null;
    currentValue?: string | null;
    updatedAt?: string | null;
    updatedBy?: string | null;
};

export type MessageDetailResponse = {
    id: string;
    sourceId: string;
    namespace: string;
    key: string;
    locale: string;
    defaultValue: string;
    overrideValue?: string | null;
    format: MessageFormat;
    arguments: {
        [key: string]: string;
    };
    needsReview: boolean;
    state: string;
    sourceRevision: string;
    defaultChecksum: string;
    version?: number | null;
    updatedAt?: string | null;
    updatedBy?: string | null;
};

export type MessageFormat = 'PlainText' | 'Icu' | 'I18NextV4';

export type MessageKeyListResponse = {
    items: Array<MessageKeyResponse>;
    page: number;
    pageSize: number;
    total: number;
    referenceLocale: string;
    targetLocale: string;
    compareLocales: Array<string>;
};

export type MessageKeyReference = {
    id: string;
    version?: number | null;
};

export type MessageKeyReferenceResponse = {
    items: Array<MessageKeyReference>;
    limit: number;
    capped: boolean;
};

export type MessageKeyResponse = {
    sourceId: string;
    namespace: string;
    key: string;
    format: MessageFormat;
    arguments: {
        [key: string]: string;
    };
    cells: {
        [key: string]: MessageCellResponse;
    };
    coverage: {
        [key: string]: MessageLocaleState;
    };
    matchedLocales: Array<string>;
};

export type MessageKeySort = 'Key' | 'UpdatedAt' | 'Status';

export type MessageKeyStatusFilter = 'All' | 'Absent' | 'Default' | 'Overridden' | 'NeedsReview' | 'Removed';

export type MessageListItem = {
    id: string;
    sourceId: string;
    namespace: string;
    key: string;
    locale: string;
    defaultPreview: string;
    overridePreview?: string | null;
    hasOverride: boolean;
    needsReview: boolean;
    state: string;
    version?: number | null;
};

export type MessageListResponse = {
    items: Array<MessageListItem>;
    page: number;
    pageSize: number;
    total: number;
};

export type MessageLocaleState = 'Default' | 'Overridden' | 'NeedsReview' | 'Removed' | 'Absent';

export type MessageStatusFilter = 'All' | 'Default' | 'Overridden' | 'NeedsReview' | 'Missing';

export type NamespaceMode = 'Fixed' | 'FirstSegment';

export type NestedJsonParserOptions = {
    locales: Array<string>;
    namespace: string;
    namespaceMode: NamespaceMode;
    messageFormat: MessageFormat;
};

export type OutputConflictResponse = {
    locale: string;
    namespace: string;
    messageFormats: Array<MessageFormat>;
};

export type OutputEndpointResponse = {
    locale: string;
    namespace: string;
    format: TranslationOutputFormat;
};

export type OverrideRequest = {
    sourceId: string;
    namespace: string;
    key: string;
    locale: string;
    value: string;
    expectedVersion?: number | null;
};

export type PermissionsResponse = {
    canView: boolean;
    canEdit: boolean;
    canManageSources: boolean;
    canSync: boolean;
};

export type ResetOverrideRequest = {
    sourceId: string;
    namespace: string;
    key: string;
    locale: string;
    expectedVersion?: number | null;
};

export type SortDirection = 'Ascending' | 'Descending';

export type SourceRequest = {
    alias: string;
    displayName: string;
    enabled: boolean;
    endpointTemplate: string;
    secretName?: string | null;
    timeoutSeconds: number;
    maximumResponseBytes: number;
    locales: Array<string>;
    namespace: string;
    namespaceMode: NamespaceMode;
    messageFormat: MessageFormat;
    headers?: Array<HttpTranslationHeaderOptions> | null;
};

export type SourceResponse = {
    id: string;
    alias: string;
    displayName: string;
    enabled: boolean;
    transport: HttpTranslationTransportOptions;
    parser: NestedJsonParserOptions;
    lastSuccessfulRevision?: string | null;
    lastSuccessfulSync?: string | null;
    syncInProgress: boolean;
    syncLeaseExpiresAt?: string | null;
    lastSync?: TranslationSyncResult;
};

export type TranslationOutputFormat = 'next-intl' | 'i18next-v4';

export type TranslationSourceMessage = {
    namespace: string;
    key: string;
    locale: string;
    value: string;
    format: MessageFormat;
    arguments: {
        [key: string]: string;
    };
    checksum: string;
};

export type TranslationSourceTestResult = {
    success: boolean;
    revision: string;
    locales: Array<string>;
    messageCount: number;
    sample: Array<TranslationSourceMessage>;
    warnings: Array<string>;
};

export type TranslationSyncResult = {
    syncId: string;
    sourceId: string;
    revision: string;
    startedAt: string;
    completedAt: string;
    status: TranslationSyncStatus;
    addedCount: number;
    changedCount: number;
    missingCount: number;
    invalidCount: number;
    error?: string | null;
};

export type TranslationSyncStatus = 'Running' | 'Succeeded' | 'Failed' | 'NotModified';

export type MessagesGetMessageFacetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/translations/facets';
};

export type MessagesGetMessageFacetsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type MessagesGetMessageFacetsResponses = {
    /**
     * OK
     */
    200: FacetResponse;
};

export type MessagesGetMessageFacetsResponse = MessagesGetMessageFacetsResponses[keyof MessagesGetMessageFacetsResponses];

export type HealthGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/translations/health';
};

export type HealthGetHealthErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type HealthGetHealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MessagesListMessagesData = {
    body?: never;
    path?: never;
    query?: {
        locale?: string;
        namespace?: string;
        query?: string;
        status?: MessageStatusFilter;
        page?: number;
        pageSize?: number;
    };
    url: '/umbraco/management/api/v1/translations/messages';
};

export type MessagesListMessagesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type MessagesListMessagesResponses = {
    /**
     * OK
     */
    200: MessageListResponse;
};

export type MessagesListMessagesResponse = MessagesListMessagesResponses[keyof MessagesListMessagesResponses];

export type MessagesGetMessageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/translations/messages/{id}';
};

export type MessagesGetMessageErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type MessagesGetMessageResponses = {
    /**
     * OK
     */
    200: MessageDetailResponse;
};

export type MessagesGetMessageResponse = MessagesGetMessageResponses[keyof MessagesGetMessageResponses];

export type MessageKeysListMessageKeysData = {
    body?: never;
    path?: never;
    query?: {
        locale?: string;
        referenceLocale?: string;
        compare?: Array<string>;
        sourceId?: string;
        namespace?: string;
        keyPrefix?: string;
        query?: string;
        status?: MessageKeyStatusFilter;
        sort?: MessageKeySort;
        direction?: SortDirection;
        page?: number;
        pageSize?: number;
    };
    url: '/umbraco/management/api/v1/translations/messages/keys';
};

export type MessageKeysListMessageKeysErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type MessageKeysListMessageKeysResponses = {
    /**
     * OK
     */
    200: MessageKeyListResponse;
};

export type MessageKeysListMessageKeysResponse = MessageKeysListMessageKeysResponses[keyof MessageKeysListMessageKeysResponses];

export type MessageKeysListMessageKeyIdsData = {
    body?: never;
    path?: never;
    query?: {
        locale?: string;
        referenceLocale?: string;
        sourceId?: string;
        namespace?: string;
        keyPrefix?: string;
        query?: string;
        status?: MessageKeyStatusFilter;
        limit?: number;
    };
    url: '/umbraco/management/api/v1/translations/messages/keys/ids';
};

export type MessageKeysListMessageKeyIdsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type MessageKeysListMessageKeyIdsResponses = {
    /**
     * OK
     */
    200: MessageKeyReferenceResponse;
};

export type MessageKeysListMessageKeyIdsResponse = MessageKeysListMessageKeyIdsResponses[keyof MessageKeysListMessageKeyIdsResponses];

export type MessagesSaveOverrideData = {
    body?: OverrideRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/translations/messages/override';
};

export type MessagesSaveOverrideErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: MessageConflictResponse;
};

export type MessagesSaveOverrideError = MessagesSaveOverrideErrors[keyof MessagesSaveOverrideErrors];

export type MessagesSaveOverrideResponses = {
    /**
     * OK
     */
    200: MessageDetailResponse;
};

export type MessagesSaveOverrideResponse = MessagesSaveOverrideResponses[keyof MessagesSaveOverrideResponses];

export type MessagesResetOverrideData = {
    body?: ResetOverrideRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/translations/messages/override/reset';
};

export type MessagesResetOverrideErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Conflict
     */
    409: MessageConflictResponse;
};

export type MessagesResetOverrideError = MessagesResetOverrideErrors[keyof MessagesResetOverrideErrors];

export type MessagesResetOverrideResponses = {
    /**
     * No Content
     */
    204: void;
};

export type MessagesResetOverrideResponse = MessagesResetOverrideResponses[keyof MessagesResetOverrideResponses];

export type PermissionsGetPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/translations/permissions';
};

export type PermissionsGetPermissionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PermissionsGetPermissionsResponses = {
    /**
     * OK
     */
    200: PermissionsResponse;
};

export type PermissionsGetPermissionsResponse = PermissionsGetPermissionsResponses[keyof PermissionsGetPermissionsResponses];

export type SourcesListSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources';
};

export type SourcesListSourcesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SourcesListSourcesResponses = {
    /**
     * OK
     */
    200: Array<SourceResponse>;
};

export type SourcesListSourcesResponse = SourcesListSourcesResponses[keyof SourcesListSourcesResponses];

export type SourcesCreateSourceData = {
    body?: SourceRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources';
};

export type SourcesCreateSourceErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type SourcesCreateSourceResponses = {
    /**
     * Created
     */
    201: SourceResponse;
};

export type SourcesCreateSourceResponse = SourcesCreateSourceResponses[keyof SourcesCreateSourceResponses];

export type SourcesDeleteSourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources/{id}';
};

export type SourcesDeleteSourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type SourcesDeleteSourceResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SourcesDeleteSourceResponse = SourcesDeleteSourceResponses[keyof SourcesDeleteSourceResponses];

export type SourcesGetSourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources/{id}';
};

export type SourcesGetSourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type SourcesGetSourceResponses = {
    /**
     * OK
     */
    200: SourceResponse;
};

export type SourcesGetSourceResponse = SourcesGetSourceResponses[keyof SourcesGetSourceResponses];

export type SourcesUpdateSourceData = {
    body?: SourceRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources/{id}';
};

export type SourcesUpdateSourceErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type SourcesUpdateSourceResponses = {
    /**
     * OK
     */
    200: SourceResponse;
};

export type SourcesUpdateSourceResponse = SourcesUpdateSourceResponses[keyof SourcesUpdateSourceResponses];

export type SourcesSyncSourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources/{id}/sync';
};

export type SourcesSyncSourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type SourcesSyncSourceResponses = {
    /**
     * OK
     */
    200: TranslationSyncResult;
};

export type SourcesSyncSourceResponse = SourcesSyncSourceResponses[keyof SourcesSyncSourceResponses];

export type SourcesListSourceSyncsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources/{id}/syncs';
};

export type SourcesListSourceSyncsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SourcesListSourceSyncsResponses = {
    /**
     * OK
     */
    200: Array<TranslationSyncResult>;
};

export type SourcesListSourceSyncsResponse = SourcesListSourceSyncsResponses[keyof SourcesListSourceSyncsResponses];

export type SourcesTestSourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources/{id}/test';
};

export type SourcesTestSourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type SourcesTestSourceResponses = {
    /**
     * OK
     */
    200: TranslationSourceTestResult;
};

export type SourcesTestSourceResponse = SourcesTestSourceResponses[keyof SourcesTestSourceResponses];

export type SourcesTestSourceConfigurationData = {
    body?: SourceRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/translations/sources/test';
};

export type SourcesTestSourceConfigurationErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type SourcesTestSourceConfigurationResponses = {
    /**
     * OK
     */
    200: TranslationSourceTestResult;
};

export type SourcesTestSourceConfigurationResponse = SourcesTestSourceConfigurationResponses[keyof SourcesTestSourceConfigurationResponses];
